name: Build and Push Python Binaries

on:
  push:
    branches:
      - main

jobs:
  build-and-push-linux:
    name: Compile on Linux and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install PyInstaller
        run: pip install -r requirements_linux.txt
      - name: Compile and move executables
        run: |
          mkdir -p bin/linux
          pyinstaller --onefile --distpath bin/linux chat.py
          pyinstaller --onefile --noconsole --distpath bin/linux client.py
          # 删缓存
          rm -rf build/ chat.spec client.spec

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Pull, add, commit, and push binaries
        run: |
          git pull --rebase
          git add bin/linux/
          git commit -m "[skip ci] [bot] Add Linux binaries" || echo "No changes to commit"
          git push

  build-and-push-windows:
    name: Compile on Windows and Push
    runs-on: windows-latest
    needs: [build-and-push-linux] # Wait for the Linux job to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install PyInstaller
        run: pip install -r requirements.txt
        
      - name: Compile and move executables
        run: |
          mkdir bin\windows
          pyinstaller --onefile --distpath bin/windows chat.py
          pyinstaller --onefile --noconsole --distpath bin/windows client.py
          # Remove PyInstaller's temporary directories
          Remove-Item -Path ".\build" -Recurse -Force
          Remove-Item -Path ".\chat.spec"
          Remove-Item -Path ".\client.spec"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Pull, add, commit, and push binaries
        run: |
          git pull --rebase
          git add bin/windows/
          git commit -m "[skip ci] [bot] Add Windows binaries" || echo "No changes to commit"
          git push
